apiVersion: v1
baseDomain: nbe.com.eg
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: cp4d
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.1.0/24
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
imageContentSources:
- mirrors:
  - mirror.nbe.com.eg:8443/cp4d/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - mirror.nbe.com.eg:8443/cp4d/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
pullSecret: ''
sshKey: ''
additionalTrustBundle: |
