apiVersion: v1
baseDomain: nbe.com.eg
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: cp4d
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"registry.cp4d.nbe.com.eg:8443":{"auth":"aW5pdDp3dlhQTG0xeU9SNDZmOUJIVlp6NzA1ZGNNdE4zODJlQQ==","email":"admin@nbe.com.eg"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDB/YvDoeXsOUREEvJHFlWLbqoAI9G1ZOaFVdmxZrXdfFQJIAAgLlz8F6YsJQIjhkR1a6Ga78txxGtDSTji/sUJ8SUrgXMkEJgx0sTO6lgZc8pbPnE/JnGSi+TsuFVPBeWy+sY+Lh5wmQzfNa/7wdu7M26n+G9jP8rYwjkhj9I8rUEAjpeZuGWAEh2DkXPWIyh5fKgS21CW/5KwyzDBjYDVO3P296l9i4zvU/D9P56skT5B3acq9aRLhZ7TSgPxLjKhXAtFA3r0FOxj30pm6E/BrLk61XnX8WAIaf2Yvay9pkwLXM8aS0uvX1/HAwvgx2NguaIVsx8JImuIhv53jg7+dFz0v29S0/ftOkoDCfNA402oXoZNdy+P66iIjPbgxk5fwhxHrNCU5Hvc6mzU3fifq5PuO47zRry97EbGXbfmBFwdw2xT5atxQ8s81tj+VT20LvXbXUFB96izep6OLQ/qsXZwch+2EDvxs6nfNLoYEA6aHM/OA/tgyvxl3NK0qfw2WjVFLi+naAnRLgEedUbElOyI61Xw7V0wf6ePIc5bWtTN52Ta4lR+9bkHQ/VI4UdoDJ5eOmTAckoILBY18Sbb8fd6j4/eOFo+E90NuWX8wlweGLYWOwL+2PLF80yepGL0UeNeoyzOw2j+5CicyJOmCZGTO8KLigGH+9VFBUgR7Q== root@registry.cp4d.nbe.com.eg'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDYzCCAkugAwIBAgIUdb3jToPkg7h7Sjvlz98Ttk5FBvUwDQYJKoZIhvcNAQEL
  BQAwcjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xITAfBgNVBAMMGHJl
  Z2lzdHJ5LmNwNGQubmJlLmNvbS5lZzAeFw0yMzA4MjUxNDQxMzlaFw0yNDA4MTUx
  NDQxMzlaMBoxGDAWBgNVBAMMD3F1YXktZW50ZXJwcmlzZTCCASIwDQYJKoZIhvcN
  AQEBBQADggEPADCCAQoCggEBAOnbG+QapUjUPwCCcUffChHfm19DaezwP8dZPIVU
  aZhvXENpbcxLADjgDfWLwRwW/tw5w1kZC/MvHVWXgi4F9N7wM0c8q17FIOPpJYlj
  GZO8wXFbJR4I6UFvP2BnEWwz0cCHqgWGfCoRXBAOxRF9SPGFRzMlQN1jvyxQ2MwY
  mmho5KB8k5l2BK/CTG1c68CKUcrgYZJFe2uwxeQXYftql2MPr7c+o9n+mYLny05b
  AaF653/IHxlTmL8z1gZMLMVQHfTeMmyw27xN1mBtV9/eF8LgW77JtbKME7U4tb8i
  4U1/96jlRvgJm6rQGpYzY0eLn5bMCfRjiq+PWQuo3W3X9xcCAwEAAaNJMEcwCwYD
  VR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCMGA1UdEQQcMBqCGHJlZ2lz
  dHJ5LmNwNGQubmJlLmNvbS5lZzANBgkqhkiG9w0BAQsFAAOCAQEAfpTCnV4WnZfp
  k0bxAZwZ2BMkFiJbGwgGj62GsRvvJOLOk8B/26Fm4K1VVPz1N308k7BBO9whVtPX
  CouDHXXb3RKMg/MqT/fDjPJUiljiApZFa2u1WB7GKGyUGasL5rQW1F1ZaSNl65Pn
  4x0ZokFjD/ALa41/3vxmRutjltcHFJW74RvDE4eb4Rp1ddEohnvM5soo4wB2SX2z
  oGEcWePEaypvXfCQmVeUgUe+mRwIYXUhGreUgkpC14qKHGCiJn/zSA04QUE67I1W
  T6lW6JwfOJ2MFzr6N3RNwl9vAHrQnXtQzdUcuy93SP/o2k0GGGdNuEJvjsC3gofm
  +u+BqfwlbQ==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIDzzCCAregAwIBAgIUDSJXweLgbE12x9UMnw2IDnrjKTUwDQYJKoZIhvcNAQEL
  BQAwcjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xITAfBgNVBAMMGHJl
  Z2lzdHJ5LmNwNGQubmJlLmNvbS5lZzAeFw0yMzA4MjUxNDQxMzVaFw0yNjA2MTQx
  NDQxMzVaMHIxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJWQTERMA8GA1UEBwwITmV3
  IFlvcmsxDTALBgNVBAoMBFF1YXkxETAPBgNVBAsMCERpdmlzaW9uMSEwHwYDVQQD
  DBhyZWdpc3RyeS5jcDRkLm5iZS5jb20uZWcwggEiMA0GCSqGSIb3DQEBAQUAA4IB
  DwAwggEKAoIBAQDAjp+9PLfouaT7dZlPazFq67f9pYU8q/hyBQwznE7T1FuLhfBw
  fzL5+zWxxybJA0geP6v2CG9mJJB2Fh3230ASvUG4EwjJ/6r8PVbpXDHymCMQsuM8
  mdEqEcSJbIjWwdUoUUPjUFir+MHDdN4wqFbBKulxMff88/CcBlCN1OGlFwCadnDP
  oYLDd/nN2f3RX370hPDket5SWIHhPVbGt/rW1aYqUPE+yCSRgsP7RYqZJVPbB5qA
  R/ZDcW/3xpNMSUsNKDr7YsjhUjjgEZMwoRQ0NFuM+akw4JGn9mntT4EJXs730/tE
  XZcZ6GKIDelqe+EJD8EwKiDKmojnQEwFDVfFAgMBAAGjXTBbMAsGA1UdDwQEAwIC
  5DATBgNVHSUEDDAKBggrBgEFBQcDATAjBgNVHREEHDAaghhyZWdpc3RyeS5jcDRk
  Lm5iZS5jb20uZWcwEgYDVR0TAQH/BAgwBgEB/wIBATANBgkqhkiG9w0BAQsFAAOC
  AQEAkwL8nQfnhhnEYr4cfAIQeWT2FDQ3017Je/DTJYgBAcfUbh2nAW76DoqbVyq/
  0/sxWgwsD4BAd/o6ApUnoKzNO/eNiWqZcnCLpVV5JFhMWMNPc9RWgcZKYYfs16Ft
  P8HyC9GmmKCRFYGNNZpxq7Wd1C+zJgEZguC46tihnuymkN/30OzH9/scUH4BJ9p1
  RmmvqOiQXH8oJ3H/DL4ss1H+4u4ocYnP0sJMDQ5isNkRyT2KtEex2EyLMwKUqWNv
  zOSPMC1YNNdV+Z4Ol52ByFjyk1zegqRZGLBWzHPKGZo9OORMT7sMihpfiUQY1B90
  OWbC/B4Kj79vOXQR9nT/uzXgag==
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.cp4d.nbe.com.eg:8443/cp4d/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.cp4d.nbe.com.eg:8443/cp4d/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
