apiVersion: project.openshift.io/v1
description: "NFS Dynamic"
displayName: nfs-dynamic-namespace
kind: ProjectRequest
metadata:
    name: nfs-dynamic-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: nfs-dynamic-namespace 
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.plz-vmware-sit-c01.nbe.ahly.bank:8443/init/nfs-subdir-external-provisioner:v4.0.2 
          volumeMounts:
            - name: nfs-client-root
              mountPath: /srv/nfs
          env:
            - name: PROVISIONER_NAME
              value: nfs-dynamic-provisioner 
            - name: NFS_SERVER
              value: 192.168.50.254
            - name: NFS_PATH
              value: /srv/nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.50.254
            path: /srv/nfs